pipeline {

    options { disableConcurrentBuilds() }
    
    agent { any }

    stages {
        stage('integrate') {
            steps {
                echo 'Merging pull-request/commit into integrate branch...'
            }
        }
        stage('build') {
            steps {
                echo 'Building...'
            }
        }
        stage('c-test') {
            steps {
                echo 'Continuous integration testing...'
            }
        }
        stage('merge') {
            steps {
                echo 'Merging integration into development branch...'
            }
        }
        stage('clean') {
            steps {
                echo 'Cleaning up...'
            }
        }
    }
    
    post {
        always {
            echo 'Ran.'
            deleteDir() /* clean up our workspace */
        }
        success {
            echo 'Passed.'
        }
        failure {
            echo 'Failed.'
        }
        unstable {
            echo 'Ran Unstabley.'
        }
        changed {
            echo 'Changed.'
        }
    }
}